### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [nityanandagohain/SoundHaven#23]
Hello, I would like to design a logo for your project. Do you have a logo? I can give some ideas if you are interested?
Greetings
Nuno

**Comment by nityanandagohain** [comment]
@nunojesus  Thank you for your interest . No we don't have a logo. Its great if you can design a logo for this project.

**Comment by AdirthaBorgohain** [comment]
Can you make it material design based?

**Comment by nunojesus** [comment]
I think I can do that. Can you tell me more about SoundHaven? What it is? What it does? It will help me with the design. If you have some idea for the logo, just tell me.

**Comment by nityanandagohain** [comment]
It is just a  cross platform music player and we used material design while developing it. No, currently no ideas from us :grinning:

**Comment by AdirthaBorgohain** [comment]
@nunojesus This is very nice. Can you use white and violet (use #673ab7) in the logo?

**Comment by nunojesus** [comment]
I Forget to explain the logo
Where do you want the violet?
![shplayerexplication](https://user-images.githubusercontent.com/34600369/39203886-0a9512ec-47ee-11e8-93b1-455b23081ff4.png)

**Comment by AdirthaBorgohain** [comment]
Can you replace red by the violet? Have to see first to decide.

**Comment by nunojesus** [comment]
I will do that and put here to show you.

**Comment by nunojesus** [comment]
![shplayer](https://user-images.githubusercontent.com/34600369/39213460-85e80ab0-4809-11e8-83c6-089d9b89ee10.png)
